### ISSUE TITLE
Maven or Bintray publishing

### ISSUE THREAD

**Issue by cypressious** [konrad-kaminski/spring-kotlin-coroutine#1]
Are you planning on publishing the artifacts?

**Comment by konrad-kaminski** [comment]
They should be available in the next few days.

**Comment by konrad-kaminski** [comment]
They are available on Bintray. See [Using in your projects](https://github.com/konrad-kaminski/spring-kotlin-coroutine#user-content-using-in-your-projects) README section for details.
