### ISSUE TITLE
How do I add request headers using CoroutineWebClient? 

### ISSUE THREAD

**Issue by asarkar** [konrad-kaminski/spring-kotlin-coroutine#13]

**Comment by konrad-kaminski** [comment]
Use the latest version (0.3.2). There you'll find methods in [`CoroutineWebClient.RequestHeadersSpec`](https://github.com/konrad-kaminski/spring-kotlin-coroutine/blob/release-0.3.2/spring-webflux-kotlin-coroutine/src/main/kotlin/org/springframework/web/coroutine/function/client/CoroutineWebClient.kt#L62). An example with customer header can be found in [`CoroutineWebClientSpec`](https://github.com/konrad-kaminski/spring-kotlin-coroutine/blob/release-0.3.2/spring-webflux-kotlin-coroutine/src/test/groovy/org/springframework/kotlin/experimental/coroutine/CoroutineWebClientSpec.groovy#L27) test.
