### ISSUE TITLE
Add missing functions in CoroutineServerResponse and CoroutineHeadersBuilder

### ISSUE THREAD

**Issue by sdeleuze** [konrad-kaminski/spring-kotlin-coroutine#24]
In `CoroutineServerResponse`:
* `from(other: CoroutineServerResponse)`
* `fun status(status: Int)`
* `fun accepted()`
* `fun noContent()`
* `fun temporaryRedirect(location: URI)`
* `fun badRequest()`
* `fun notFound()`
* `unprocessableEntity()`

+ missing functions in `CoroutineHeadersBuilder` like `header(...)`

**Comment by konrad-kaminski** [comment]
Fixed in [0.3.5](https://github.com/konrad-kaminski/spring-kotlin-coroutine/releases/tag/release-0.3.5)
