### ISSUE TITLE
Upgrade to Spring Framework 5.0

### ISSUE THREAD

**Issue by sdeleuze** [konrad-kaminski/spring-kotlin-coroutine#3]
Hey Konrad, since Spring Framework 5.0 has been recently released and now provides official Kotlin support (and not only for WebFlux level, see the [reference documentation](https://docs.spring.io/spring/docs/current/spring-framework-reference/kotlin.html)), do you have any plan to upgrade `spring-kotlin-coroutine` to support it (I guess Spring Framework 4.x users could continue to use `spring-kotlin-coroutine` 0.2.x) ?

**Comment by konrad-kaminski** [comment]
You should be able to use the current version of `spring-kotlin-coroutine` with Spring 5 - you just have to manually specify dependency to Spring 5 in your app. Of course it won't use Spring WebFlux - this is one the things I'm working on right now. In the next couple of days I should release a version which works with Spring WebFlux.

**Comment by konrad-kaminski** [comment]
The new version (0.3.0) has been released.
