### ISSUE TITLE
Support for Kotlin 1.3.0

### ISSUE THREAD

**Issue by andyswift** [konrad-kaminski/spring-kotlin-coroutine#39]
Are there any plans to migrate to the latest Kotlin release now that coroutines are no longer 'experimental'

**Comment by 0mok** [comment]
I've created a patch for supporting kotlin 1.3.0 (#40).

**Comment by lazyFloyd** [comment]
> Are there any plans to migrate to the latest Kotlin release now that coroutines are no longer 'experimental'

+1, any timeframe on a support for Kotlin 1.3+? @konrad-kaminski

**Comment by mpires** [comment]
+1

**Comment by domgom** [comment]
+1

**Comment by domgom** [comment]
I've created https://github.com/konrad-kaminski/spring-kotlin-coroutine/pull/44 with the latest Kotlin and coroutines versions and also addressed some comments* on the original https://github.com/konrad-kaminski/spring-kotlin-coroutine/pull/40 from @andyswift.

*Actually renamed all packages to remove `.experimental.` references.

**Comment by andyswift** [comment]
I see this is going to be rolled out in SpringBoot 2.2 
We have migrated to the latest milestone (2.2.0.M2) and it is working nicely

**Comment by konrad-kaminski** [comment]
Merged. Thanks @domgom .
