### ISSUE TITLE
Add Coroutine based alternative to Reactive Spring WebFlux APIs

### ISSUE THREAD

**Issue by sdeleuze** [konrad-kaminski/spring-kotlin-coroutine#4]
As discussed on [SPR-15413](https://jira.spring.io/browse/SPR-15413), and based on your experiment on MiXiT application, any chance you could provide Coroutine based alternative to Spring WebFlux Reactive APIs? That would be especially a good fit with Kotlin server DSL and `WebClient`.

**Comment by konrad-kaminski** [comment]
Working on that right now. Should be ready in a couple of days.

**Comment by sdeleuze** [comment]
Awesome thanks!

**Comment by konrad-kaminski** [comment]
Ready in 0.3.0 release.
