### ISSUE TITLE
Use suspendable List<T> instead of ReceiveChannel<T> for collections in CoroutineMongoOperations

### ISSUE THREAD

**Issue by sdeleuze** [konrad-kaminski/spring-kotlin-coroutine#6]
I think it would be more relevant to use suspendable `List<T>` instead of `ReceiveChannel<T>` in methods others than `tail()` (where `ReceiveChannel` is a perfect fit). The would make `CoroutineMongoOperations` even more closer to a suspendable version of `MongoOperations` which is a good thing IMO.

**Comment by konrad-kaminski** [comment]
Fixed in [0.3.1](https://github.com/konrad-kaminski/spring-kotlin-coroutine/releases/tag/release-0.3.1).
