### ISSUE TITLE
DefaultCoroutineWebClient seems not supporting baseUrl

### ISSUE THREAD

**Issue by sdeleuze** [konrad-kaminski/spring-kotlin-coroutine#7]
`DefaultCoroutineWebClient` seems not supporting `baseUrl` definition at `WebClient` level. For example, see https://github.com/sdeleuze/spring-kotlin-deepdive/blob/step3-coroutine/src/test/kotlin/io/spring/deepdive/HtmlTests.kt which fails if you define `DefaultCoroutineWebClient(WebClient.create("http://localhost:$port"))` and just use relative url like `client.get().uri("/api/user/")`.

**Comment by konrad-kaminski** [comment]
Fixed in [0.3.1](https://github.com/konrad-kaminski/spring-kotlin-coroutine/releases/tag/release-0.3.1).

Use `CoroutineWebClient.create("http://localhost:$port").get().uri("/api/user/")`.
