### ISSUE TITLE
Missing methods in CoroutineWebClient

### ISSUE THREAD

**Issue by sdeleuze** [konrad-kaminski/spring-kotlin-coroutine#8]
Please find bellow extensions that I had to create, I think these 2 methods should be available by default.

```inline suspend fun <reified T : Any> CoroutineWebClient.CoroutineResponseSpec.body() = body(T::class.java)```

```fun CoroutineWebClient.RequestHeadersUriSpec<*>.uri(uri: String) = uri(URI(uri))```

**Comment by konrad-kaminski** [comment]
Fixed in [0.3.1](https://github.com/konrad-kaminski/spring-kotlin-coroutine/releases/tag/release-0.3.1)
